# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogArtcile',
            new_name='BlogArtciles',
        ),
    ]
